"""Add Yard Check Audit System

Revision ID: 73515f13166c
Revises: cdbf0dfcfa5b
Create Date: 2026-04-06 21:23:01.427687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73515f13166c'
down_revision: Union[str, Sequence[str], None] = 'cdbf0dfcfa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yard_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yard_checks_id'), 'yard_checks', ['id'], unique=False)
    op.create_index(op.f('ix_yard_checks_region_id'), 'yard_checks', ['region_id'], unique=False)
    op.create_table('yard_check_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yard_check_id', sa.Integer(), nullable=True),
    sa.Column('trailer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('VERIFIED', 'FIXED', 'MISSING', name='auditstatus'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trailer_id'], ['trailers.id'], ),
    sa.ForeignKeyConstraint(['yard_check_id'], ['yard_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_yard_check_items_id'), 'yard_check_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yard_check_items_id'), table_name='yard_check_items')
    op.drop_table('yard_check_items')
    op.drop_index(op.f('ix_yard_checks_region_id'), table_name='yard_checks')
    op.drop_index(op.f('ix_yard_checks_id'), table_name='yard_checks')
    op.drop_table('yard_checks')
    # ### end Alembic commands ###
