"""Update Trailer and Task models for auto-suggestion

Revision ID: b797571a19c9
Revises: f37f66c36fbf
Create Date: 2026-04-06 21:13:47.554840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b797571a19c9'
down_revision: Union[str, Sequence[str], None] = 'f37f66c36fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shunt_tasks', sa.Column('to_dock_door_id', sa.Integer(), nullable=True))
    op.add_column('shunt_tasks', sa.Column('req_trailer_type', sa.String(), nullable=True))
    op.add_column('shunt_tasks', sa.Column('req_is_loaded', sa.Boolean(), nullable=True))
    op.add_column('shunt_tasks', sa.Column('req_min_size', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shunt_tasks', 'dock_doors', ['to_dock_door_id'], ['id'])
    op.add_column('trailers', sa.Column('trailer_type', sa.String(), nullable=True))
    op.add_column('trailers', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('trailers', sa.Column('shipping_line', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trailers', 'shipping_line')
    op.drop_column('trailers', 'size')
    op.drop_column('trailers', 'trailer_type')
    op.drop_constraint(None, 'shunt_tasks', type_='foreignkey')
    op.drop_column('shunt_tasks', 'req_min_size')
    op.drop_column('shunt_tasks', 'req_is_loaded')
    op.drop_column('shunt_tasks', 'req_trailer_type')
    op.drop_column('shunt_tasks', 'to_dock_door_id')
    # ### end Alembic commands ###
