"""Add Vehicles and Access Logs

Revision ID: cdbf0dfcfa5b
Revises: b797571a19c9
Create Date: 2026-04-06 21:21:18.821156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbf0dfcfa5b'
down_revision: Union[str, Sequence[str], None] = 'b797571a19c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('current_driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_region_id'), 'vehicles', ['region_id'], unique=False)
    op.create_index(op.f('ix_vehicles_unit_number'), 'vehicles', ['unit_number'], unique=True)
    op.create_table('vehicle_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_logs_id'), 'vehicle_logs', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_logs_region_id'), 'vehicle_logs', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_logs_region_id'), table_name='vehicle_logs')
    op.drop_index(op.f('ix_vehicle_logs_id'), table_name='vehicle_logs')
    op.drop_table('vehicle_logs')
    op.drop_index(op.f('ix_vehicles_unit_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_region_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
