"""Initial migration: Trailer table

Revision ID: dd7a31e3a20f
Revises: 
Create Date: 2026-04-06 19:02:41.423159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7a31e3a20f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trailers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('trailer_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_loaded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trailers_id'), 'trailers', ['id'], unique=False)
    op.create_index(op.f('ix_trailers_region_id'), 'trailers', ['region_id'], unique=False)
    op.create_index(op.f('ix_trailers_trailer_number'), 'trailers', ['trailer_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trailers_trailer_number'), table_name='trailers')
    op.drop_index(op.f('ix_trailers_region_id'), table_name='trailers')
    op.drop_index(op.f('ix_trailers_id'), table_name='trailers')
    op.drop_table('trailers')
    # ### end Alembic commands ###
