"""Add DockDoors and ShuntTasks

Revision ID: f37f66c36fbf
Revises: 1b6e4c02101c
Create Date: 2026-04-06 21:06:00.975047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37f66c36fbf'
down_revision: Union[str, Sequence[str], None] = '1b6e4c02101c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dock_doors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('door_number', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('current_trailer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_trailer_id'], ['trailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dock_doors_door_number'), 'dock_doors', ['door_number'], unique=False)
    op.create_index(op.f('ix_dock_doors_id'), 'dock_doors', ['id'], unique=False)
    op.create_index(op.f('ix_dock_doors_region_id'), 'dock_doors', ['region_id'], unique=False)
    op.create_table('shunt_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('trailer_id', sa.Integer(), nullable=True),
    sa.Column('from_location', sa.String(), nullable=True),
    sa.Column('to_location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'ASSIGNED', 'ACCEPTED', 'PINNED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='taskstatus'), nullable=True),
    sa.Column('assigned_driver_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trailer_id'], ['trailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shunt_tasks_id'), 'shunt_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_shunt_tasks_region_id'), 'shunt_tasks', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shunt_tasks_region_id'), table_name='shunt_tasks')
    op.drop_index(op.f('ix_shunt_tasks_id'), table_name='shunt_tasks')
    op.drop_table('shunt_tasks')
    op.drop_index(op.f('ix_dock_doors_region_id'), table_name='dock_doors')
    op.drop_index(op.f('ix_dock_doors_id'), table_name='dock_doors')
    op.drop_index(op.f('ix_dock_doors_door_number'), table_name='dock_doors')
    op.drop_table('dock_doors')
    # ### end Alembic commands ###
